In [36]:
import numpy as np
d = np.zeros((2,4))
a = np.arange(24).reshape((2,3,4))
b = a.reshape((6,4))

print('a',a)
print('b',b)
c = np.random.randint(0,6,(20)).reshape(4,5)
print('c',c)
e = b[c,:]
print(e.shape)
print('e',e)
a = np.zeros((3,4,5))

a [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
b [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
c [[4 2 4 5 1]
 [2 3 4 3 3]
 [4 1 3 1 3]
 [3 0 4 5 5]]
(4, 5, 4)
e [[[16 17 18 19]
  [ 8  9 10 11]
  [16 17 18 19]
  [20 21 22 23]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]
  [16 17 18 19]
  [12 13 14 15]
  [12 13 14 15]]

 [[16 17 18 19]
  [ 4  5  6  7]
  [12 13 14 15]
  [ 4  5  6  7]
  [12 13 14 15]]

 [[12 13 14 15]
  [ 0  1  2  3]
  [16 17 18 19]
  [20 21 22 23]
  [20 21 22 23]]]
